[package]
name = "look-cashier"
version = "2.0.0"
description = "ASAS MARKET POS - Managed by ASAS Software Solutions"
authors = ["ASAS Software Solutions"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
